import {Dimensions} from 'react-native';
import {heightToDp, widthToDp} from './ResponsiveComponent';

export default {
  styleHeadingView: {
    flexDirection: 'row',
    padding: 10,
    width: '100%',
  },
  stylesHeadingText: {
    fontSize: 16,
    color: '#1C72C3',
    width: '90%',
  },
  touchableIconRowAdditionalStyle: {
    alignItems: 'flex-start',
    paddingTop: 0,
    paddingHorizontal: 18,
  },
  styleDetailsView: {
    left: '10.5%',
    borderWidth: 1,
    borderRadius: 15,
    width: '87%',
    borderColor: '#E2E7EA',
    paddingHorizontal: 15,
    paddingVertical: 5,
    backgroundColor: '#E2E7EA',
  },
  styleDetailsViewTrophy: {
    margin: 20,
    borderRadius: 15,
    paddingHorizontal: 15,
    paddingVertical: 5,
    backgroundColor: '#E2E7EA',
  },
  styleHeadingTrophy: {
    fontSize: 12,
    color: '#566573',
    width: '43%',
  },
  styleDetailsTrophy: {
    fontSize: 12,
    color: '#7621BD',
    width: '55%',
  },
  additionalStyleForStumping: {
    justifyContent: 'space-between',
    borderBottomWidth: 0,
    paddingHorizontal: 0,
  },
  fontWeightBold: {fontWeight: 'bold'},
  fontStyleItalic: {fontStyle: 'italic'},
  fontBoldUnderlined: {
    fontWeight: 'bold',
    textDecorationLine: 'underline',
  },
  styleEachDetailItemView: {
    flexDirection: 'row',
    paddingVertical: 6,
    borderBottomWidth: 0.8,
    borderColor: '#cdcdcd',
    width: '100%',
  },
  styleYearLeftText: {
    fontSize: 13,
    color: '#566573',
    width: '15%',
  },
  styleDescRightText: {
    fontSize: 13,
    color: '#7621BD',
    width: '85%',
  },
  styleTournamentTableColumnStyle: {
    width: '25%',
    color: '#566573',
    textAlign: 'center',
    borderRightWidth: 1,
    borderRightColor: '#cdcdcd',
  },
  styleBoxHeadingView: {
    flexDirection: 'row',
    margin: 10,
    paddingVertical: 5,
    paddingLeft: 5,
    paddingRight: 15,
    backgroundColor: '#fff',
    justifyContent: 'space-between',
    alignItems: 'center',
    elevation: 2,
    borderWidth: 1,
    borderRadius: 5,
    borderColor: '#fafafa',
  },
  styleCommentTesterText: {
    marginHorizontal: 5,
    color: '#1C72C3',
    padding: 5,
    fontSize: 19,
  },
  alignItemsCenter: {alignItems: 'center'},
  padding: {
    padding: 5,
  },
  styleEachTouchableInRow: {
    width: '100%',
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderWidth: 1,
    borderRadius: 10,
    borderColor: '#008000',
    backgroundColor: '#008000',
  },
  topPerformanesImageShowStyle: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#CACECB',
    height: 40,
    width: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 40 / 2,
  },
  justifyContentCenter: {justifyContent: 'center'},
  extraTextStyleForTopPerformanceAnalysis: {
    color: '#fff',
    fontSize: 16,
    textAlign: 'center',
  },
  fontItalicUnderlined: {
    fontStyle: 'italic',
    textDecorationLine: 'underline',
  },
  left: {left: '10.5%'},
  fontUnderlined: {textDecorationLine: 'underline'},
  movieIconRowStyle: {
    flexDirection: 'row',
    paddingHorizontal: 43,
    alignItems: 'center',
  },
  //header styles
  styleHeaderOuterContainer: {backgroundColor: '#0095ba'},
  styleHeaderInnerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: '3%',
    paddingVertical: '2%',
  },
  styleHeaderTitle: {
    fontSize: 19,
    paddingLeft: 10,
    color: '#fff',
  },
  //modal styles
  modalOuterStyle: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: 'rgba(37, 8, 10, 0.50)',
    alignItems: 'center',
  },
  modalCloseStyle: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 35,
    height: 35,
    backgroundColor: '#fff',
    borderRadius: 35 / 2,
    elevation: 5,
    marginTop: 5,
  },
  developerContactStyle: {
    position: 'absolute',
    bottom: 0,
    padding: heightToDp('1%'),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  developerContactTextStyle: {
    color: '#ffd700',
    fontWeight: 'bold',
  },
  devContactTouchableStyle: {
    width: widthToDp('80%'),
    paddingVertical: heightToDp('2%'),
    paddingHorizontal: widthToDp('10%'),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#ffd700',
    borderRadius: 20,
  },
  devContactTextStyle: {
    color: '#72246C',
    fontSize: widthToDp('6%'),
    paddingLeft: widthToDp('0.5%'),
  },
  wtsAppDevContactTextFieldStyle: {
    width: widthToDp('60%'),
    borderBottomWidth: 1,
    borderColor: '#808080',
    fontSize: widthToDp('4%'),
  },
};
